name: Slack → Notion (links)

on:
  # Run every 30 minutes (UTC). Adjust as you like.
  schedule:
    - cron: "*/30 * * * *"
  # Allow manual runs from the Actions tab
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest

    # Avoid overlapping runs if a previous one is still going
    concurrency:
      group: slack-to-notion
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run harvester
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: |
          python test_slack_script.py
